### ISSUE TITLE
Action fails on apt update

### ISSUE THREAD

**Issue by kornys** [manusa/actions-setup-minikube#34]
I see that minikube action is not able to complete apt update.

```
Get:46 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [80.7 kB]
Get:47 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [10.6 kB]
Get:48 http://ppa.launchpad.net/git-core/ppa/ubuntu focal/main amd64 Packages [3056 B]
Get:49 https://dl.bintray.com/sbt/debian  Packages [5122 B]
Get:50 https://apt.postgresql.org/pub/repos/apt focal-pgdg/main amd64 Packages [191 kB]
Reading package lists...
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' no longer has a Release file.
Error: Command failed: sudo apt-get update
Error: Command failed: sudo apt-get update
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at logExecSync (/home/runner/work/_actions/manusa/actions-setup-minikube/v2.3.0/src/exec.js:8:17)
    at configureEnvironment (/home/runner/work/_actions/manusa/actions-setup-minikube/v2.3.0/src/configure-environment.js:25:3)
    at run (/home/runner/work/_actions/manusa/actions-setup-minikube/v2.3.0/src/index.js:14:9)
    at Object.<anonymous> (/home/runner/work/_actions/manusa/actions-setup-minikube/v2.3.0/src/index.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  status: 100,
  signal: null,
  output: [ null, null, null ],
  pid: 1498,
  stdout: null,
  stderr: null
}
Error: Command failed: sudo apt-get update
```

**Comment by leseb** [comment]
Same on 18.04. Looks like things changed a bit here: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable, today. 🤷‍♂️

**Comment by leseb** [comment]
FYI, it's working again on my side 🥳

**Comment by manusa** [comment]
It seems like an intermittent failure, something wrong with the Open Suse repo.
I'm cutting a new release with something that should fix it for all runs 🤞

**Comment by leseb** [comment]
Perhaps a repo caching issue.

**Comment by manusa** [comment]
Given the timestamps in https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable
![image](https://user-images.githubusercontent.com/488391/111182585-5793b100-85af-11eb-8215-83cc8dbd670e.png)

and https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/
![image](https://user-images.githubusercontent.com/488391/111182517-4480e100-85af-11eb-831e-3c16905a941e.png)

Probably had something to do with a failed release process in Open Suse. Actions seem to pass now, not sure if the fix actually does something or not. Anyway, there's a [v2.3.1](https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v2.3.1) out
