### ISSUE TITLE
Sorry, Kubernetes v1.18.2 requires conntrack to be installed in root's path

### ISSUE THREAD

**Issue by joan38** [manusa/actions-setup-minikube#7]
```
* Using the none driver based on user configuration
X Sorry, Kubernetes v1.18.2 requires conntrack to be installed in root's path
Error: Command failed: sudo -E /home/runner/work/_temp/minikube start --vm-driver=none --kubernetes-version v1.18.2
##[error]Command failed: sudo -E /home/runner/work/_temp/minikube start --vm-driver=none --kubernetes-version v1.18.2
##[error]Command failed: sudo -E /home/runner/work/_temp/minikube start --vm-driver=none --kubernetes-version v1.18.2
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at logExecSync (/home/runner/work/_actions/manusa/actions-setup-minikube/v1.0.1/src/exec.js:8:17)
    at install (/home/runner/work/_actions/manusa/actions-setup-minikube/v1.0.1/src/install.js:16:3)
    at async run (/home/runner/work/_actions/manusa/actions-setup-minikube/v1.0.1/src/index.js:16:3) {
```
https://github.com/joan38/kubernetes-client/pull/13/checks?check_run_id=598510562

See minikube issue:
https://github.com/kubernetes/minikube/issues/7659

**Comment by manusa** [comment]
Thanks for reporting.
 
I'll try to address and publish a new release.

**Comment by guilhermelionzo** [comment]
Hi @joan38 , 

I was struggling in the same error and installing **conntrack** solved the problem. 

The command bellow should solve the issue:

`sudo apt-get install -y conntrack`

**Comment by manusa** [comment]
Hi,

Version [v1.0.2](https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster?version=v1.0.2) has been released with a fix addressing the issue.

Thanks for reporting and trying out the action. I was completely unaware that there were other people using this around the community :smiley:.

**Comment by dipon21** [comment]
yum install conntrack
minikube start --driver=none   for centos

it worked

**Comment by manaschandrasahoo** [comment]
thanks it is also solved my problem also.

**Comment by Jkudjo** [comment]
sudo apt-get install -y conntrack

solved it , Thanks @guilhermelionzo

**Comment by hkalsait** [comment]
1. You need to update your system by using the below commands,
For Ubuntu/Debian -`sudo apt update && sudo apt upgrade` OR For RHEL/CentOS - `sudo yum update && sudo yum upgrade`
2.  As well as Need to download the tar package from [Github](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md) by using the below wget command. This will download the package in your local directory of your System.
`wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz`

**Comment by Joelfernandes30** [comment]
Thank you it worked

**Comment by DPS0340** [comment]
On arch linux:

`sudo pacman -Syu conntrack-tools`

**Comment by HerryCloud007** [comment]
Thank you @hkalsait, it worked for me too !!

**Comment by jgrandydev** [comment]
```
x@y:/mnt/c/Users/x$ minikube start --driver=none
😄  minikube v1.34.0 on Ubuntu 24.04 (amd64)
✨  Using the none driver based on user configuration

❌  Exiting due to GUEST_MISSING_CONNTRACK: Sorry, Kubernetes 1.31.0 requires conntrack to be installed in root's path

x@y:/mnt/c/Users/x$ sudo apt install -y conntrack
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  conntrack
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 37.9 kB of archives.
After this operation, 119 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 conntrack amd64 1:1.4.8-1ubuntu1 [37.9 kB]
Fetched 37.9 kB in 0s (78.5 kB/s)
Selecting previously unselected package conntrack.
(Reading database ... 41331 files and directories currently installed.)
Preparing to unpack .../conntrack_1%3a1.4.8-1ubuntu1_amd64.deb ...
Unpacking conntrack (1:1.4.8-1ubuntu1) ...
Setting up conntrack (1:1.4.8-1ubuntu1) ...
Processing triggers for man-db (2.12.0-4build2) ...

x@y:/mnt/c/Users/x$ minikube start --driver=none
😄  minikube v1.34.0 on Ubuntu 24.04 (amd64)
✨  Using the none driver based on user configuration

❌  Exiting due to GUEST_MISSING_CONNTRACK: Sorry, Kubernetes 1.31.0 requires crictl to be installed in root's path

x@y:/mnt/c/Users/x$ sudo apt install -y crictl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package crictl

x@y:/mnt/c/Users/x$ minikube start --driver=none
😄  minikube v1.34.0 on Ubuntu 24.04 (amd64)
✨  Using the none driver based on user configuration

❌  Exiting due to GUEST_MISSING_CONNTRACK: Sorry, Kubernetes 1.31.0 requires crictl to be installed in root's path
```
