### ISSUE TITLE
failed to expand crictl tar file

### ISSUE THREAD

**Issue by satoru-takeuchi** [manusa/actions-setup-minikube#70]
Sometimes expanding crictl failed with the following error.

https://github.com/rook/rook/actions/runs/3039246303/jobs/4901187676#step:3:93
```
Downloading cri-ctl
Downloading from: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.25.0/crictl-v1.25.0-linux-amd64.tar.gz
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /usr/local/bin -f /home/ubuntu/actions-runner/_work/_temp/fc1ec1bc-435b-4d1b-8e29-6c7d9a384280
/usr/bin/tar: crictl: Cannot open: Permission denied
/usr/bin/tar: Exiting with failure status due to previous errors
Error: The process '/usr/bin/tar' failed with exit code 2
    at ExecState._setResult (/home/ubuntu/actions-runner/_work/_actions/manusa/actions-setup-minikube/v2.7.0/node_modules/@actions/exec/lib/toolrunner.js:5[92](https://github.com/rook/rook/actions/runs/3039246303/jobs/4901187676#step:3:96):25)
    at ExecState.CheckComplete (/home/ubuntu/actions-runner/_work/_actions/manusa/actions-setup-minikube/v2.7.0/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/ubuntu/actions-runner/_work/_actions/manusa/actions-setup-minikube/v2.7.0/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
Error: The process '/usr/bin/tar' failed with exit code 2
Error: The process '/usr/bin/tar' failed with exit code 2
```

Interestingly, once this happens, re-running failed test results failed again at a high rate.

I hit this problem in v2.7.0. I've not confirmed whether this problem exists in other versions.

**Comment by satoru-takeuchi** [comment]
This problem only happens if github actions runner is aarch64 machine. Does actions-setup-minikube support aarch64?

**Comment by satoru-takeuchi** [comment]
This problem happened due to the misconfiguration of my self-hosted-runner. Sorry for the noise.

**Comment by retraut** [comment]
How do you fix it?

**Comment by satoru-takeuchi** [comment]
@retraut I completely forgot it because this problem happened two years ago and I lost troubleshooting log.
